import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
			<pre>Soy el layout de about</pre>
			{children}
		</>
  )
}
